name: Benchmark torch.compile models nightly

on:
  # run every day at 9:15pm
  schedule:
    - cron:  '15 21 * * *'

permissions:
  contents: read

jobs:
  nightly:
    strategy:
      fail-fast: false
    runs-on: [self-hosted, gpu]
    timeout-minutes: 1320
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Clean up previous run
        run: |
          echo "Cleaning up previous run"
          cd $RUNNER_WORKSPACE
          pwd
          cd ..
          pwd
          rm -rf _tool
      - name: Setup Python 3.10
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: "3.10"
          architecture: x64
      - name: Setup Java 17
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y apache2-utils
          pip install -r benchmarks/requirements-ab.txt
      - name: Install model-specific dependencies
        run: |
          chmod +x benchmarks/benchmark_model_dependencies.sh
          source benchmarks/benchmark_model_dependencies.sh
      - name: Benchmark gpu nightly
        run: python benchmarks/auto_benchmark.py --input benchmarks/benchmark_config_torch_compile_gpu.yaml --skip false --nightly True
