name: CI CPU - CPP Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci-cpu-cpp:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    steps:
      # - name: Setup Python for M1
      #   if: matrix.os == 'macos-14'
      #   uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      #   with:
      #     python-version: '3.10'
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Setup Python for all other OS
        if: matrix.os != 'macos-14'
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.9
          architecture: x64
      - name: Setup Java 17
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive
      # - name: Install libtorch - macOS
      #   if: matrix.os == 'macOS-latest'
      #   run: |
      #       brew install libtorch
      - name: Install dependencies
        run: |
          sudo apt update && python ts_scripts/install_dependencies.py --environment=dev --cpp
      - name: Install TorchServe
        run: |
          python ts_scripts/install_from_src.py
      - name: Print Env
        run: |
          python ts_scripts/print_env_info.py
      - name: Build
        run: |
          cd cpp && rm -rf _build && sudo mkdir /mnt/_build && sudo chmod 777 /mnt/_build && mkdir build && sudo mount --bind /mnt/_build build
          cd build && cmake ..
          make -j && make install
          make test
      - name: Run test
        run: |
          cd test && pytest pytest/test_cpp_backend.py
