name: CI GPU

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:

concurrency:
  group: ci-gpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci-gpu:
    runs-on: [self-hosted, ci-gpu]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Clean up previous run
        run: |
          echo "Cleaning up previous run"
          ls -la ./
          # deletes all files in the current directory
          sudo rm -rf ./* || true
          # deletes all hidden files in a directory
          sudo rm -rf ./.??* || true
          ls -la ./
      - name: Setup Python 3.9
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.9
          architecture: x64
      - name: Setup Java 17
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          python ts_scripts/install_dependencies.py --environment=dev --cuda=cu121
      - name: Torchserve Sanity
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 60
          retry_on: error
          max_attempts: 3
          command: |
            python torchserve_sanity.py

      # Any coverage.xml will be picked up by this step
      # Just make sure each coverage.xml is in a different folder
      - name: Upload codecov
        run : |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
