on:
  push:
    branches:
      - master
  merge_group:

permissions:
  contents: read

jobs:
  build_docs_job:
    runs-on: ubuntu-20.04
    permissions:
      # Grant write permission here so that the doc can be pushed to gh-pages branch
      contents: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit

    - name: Setup Python 3.9
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: 3.9
        architecture: x64
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Install Dependencies
      run: |
        pip install -r ./docs/sphinx/requirements.txt
    - name: Build the docset
      run: |
        cd ./docs/sphinx
        make html
      id: build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@132898c54c57c7cc6b80eb3a89968de8fc283505 # releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/sphinx/build/html
          CLEAN_EXCLUDE: '["_config.yml"]'
    - name: Open issue on failure
      if: ${{ failure() && github.event_name  == 'schedule' }}
      uses: dacbd/create-issue-action@ba4d1c45cccf9c483f2720cefb40e437f0ee6f7d # v1.2.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Doc automation failed
        body:  Commit ${{ github.sha }} daily scheduled [CI run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed, please check why
        assignees: ''
