name: Push Docker Nightly

on:
  # Run every day at 1:15pm
  schedule:
    - cron: "15 13 * * *"
  workflow_dispatch:

jobs:
  nightly:
    runs-on: [self-hosted, ci-gpu]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Clean up previous run
        run: |
          echo "Cleaning up previous run"
          ls -la ./
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
          ls -la ./
      - name: Setup Python 3.9
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.9
          architecture: x64
      - name: Checkout TorchServe
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive
      - name: Login to Docker
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login --username pytorchbot --password "$DOCKER_PASSWORD"
      - name: Push Docker Nightly
        run: |
          cd docker
          sudo apt-get update
          docker buildx use multibuilder
          python docker_nightly.py --cleanup
      - name: Push KServe Docker Nightly
        run: |
          cd kubernetes/kserve
          docker buildx use multibuilder
          python docker_nightly.py --cleanup
      - name: Open issue on failure
        if: ${{ failure() && github.event_name  == 'schedule' }}
        uses: dacbd/create-issue-action@ba4d1c45cccf9c483f2720cefb40e437f0ee6f7d # v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Nightly Docker build failed
          body: Commit ${{ github.sha }} daily scheduled [CI run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed, please check why
          assignees: ""
