name: KServe CPU Nightly Tests

on:
  workflow_dispatch:
  # runs everyday  at 5:15am
  schedule:
    - cron:  '15 5 * * *'

permissions:
  contents: read

jobs:
  kserve-cpu-tests:
    runs-on: [self-hosted, regression-test-gpu]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Clean up previous run
        run: |
          echo "Cleaning up previous run"
          ls -la ./
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
          ls -la ./
      - name: Install minikube and kubectl
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          echo "/usr/local/bin" >> $GITHUB_PATH
      - name: Setup Python 3.9
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.9
          architecture: x64
      - name: Install grpcurl
        run: |
          sudo curl -sSL https://github.com/fullstorydev/grpcurl/releases/download/v1.8.0/grpcurl_1.8.0_linux_x86_64.tar.gz | sudo tar -xz -C /usr/local/bin grpcurl
          sudo chmod +x /usr/local/bin/grpcurl
      - name: Checkout TorchServe
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Checkout kserve repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: kserve/kserve
          ref: v0.12.1
          path: kserve
      - name: Validate torchserve-kfs and Open Inference Protocol
        run: ./kubernetes/kserve/tests/scripts/test_mnist.sh cpu
