name: Run Regression Tests for CPU nightly binaries

on:
  # run every day at 6:15am
  schedule:
    - cron: '15 6 * * *'

concurrency:
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  regression-cpu-nightly-binaries:
    # creates workflows for OS: ubuntu, macOS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
        binaries: ["pypi", "conda"]
        exclude:
        - os: macos-latest
          python-version: 3.8
        - os: macos-14
          python-version: 3.8
        - os: macos-14
          python-version: 3.9
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive
      - name: Setup conda with Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@505e6394dae86d6a5c7fbb6e3fb8938e3e863830 # v3.1.1
        with:
          auto-update-conda: true
          channels: anaconda, conda-forge
          python-version: ${{ matrix.python-version }}
      - name: Setup Java 17
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout TorchServe
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          echo "=====CHECK ENV AND PYTHON VERSION===="
          conda info --envs
          python --version
          echo "=====RUN INSTALL DEPENDENCIES===="
          python ts_scripts/install_dependencies.py --environment=dev
      - name: Torchserve Regression Tests
        shell: bash -el {0}
        env:
          TS_MAC_ARM64_CPU_ONLY: ${{ matrix.os == 'macos-latest' && 'True' || 'False' }}
        run: |
          echo "=====CHECK ENV AND PYTHON VERSION===="
          conda info --envs
          python --version
          echo "=====RUN REGRESSION TESTS===="
          python test/regression_tests.py --binaries --${{ matrix.binaries }} --nightly
