name: Run Regression Tests for GPU nightly binaries

on:
  # run every day at 6:15am
  schedule:
    - cron:  '15 6 * * *'

concurrency:
  group: ci-cpu-${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  regression-gpu-nightly-binaries:
    # creates workflows for 3 python versions on self hosted
    runs-on: [self-hosted, regression-test-gpu]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        binaries: ["pypi", "conda"]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Clean up previous run
        run: |
          echo "Cleaning up previous run"
          ls -la ./
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
          ls -la ./
      - name: Checkout TorchServe
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@9f54435e0e72c53962ee863144e47a4b094bfd35 # v2.3.0
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python --version
      - run: conda --version
      - name: Setup Java 17
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          echo "=====CHECK ENV AND PYTHON VERSION===="
          /home/ubuntu/actions-runner/_work/serve/serve/3/condabin/conda info --envs
          python --version
          echo "=====RUN INSTALL DEPENDENCIES===="
          python ts_scripts/install_dependencies.py --environment=dev --cuda=cu121
      - name: Torchserve Regression Tests
        shell: bash -el {0}
        run: |
          echo "=====CHECK ENV AND PYTHON VERSION===="
          /home/ubuntu/actions-runner/_work/serve/serve/3/condabin/conda info --envs
          python --version
          echo "=====RUN REGRESSION TESTS===="
          python test/regression_tests.py --binaries --${{ matrix.binaries }} --nightly
