name: Push torchserve nightly

on:
  # run every day at 11:15am
  schedule:
    - cron:  '15 11 * * *'
  workflow_dispatch:
jobs:
  nightly:
    runs-on: ubuntu-20.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Setup Conda
        uses: s-weigand/setup-conda@7e8fd4c763d3ccb2296fe2a06814d45b3e447dc7 # v1.2.4
        with:
          activate-conda: true
          update-conda: false
          python-version: "3.9"
      - run: conda --version
      - run: conda install -y conda-build anaconda-client
      - name: Checkout TorchServe
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          python ts_scripts/install_dependencies.py --environment=dev
          pip install -e .
      - name: Setup Java 17
        uses: actions/setup-java@91d3aa4956ec4a53e477c4907347b5e3481be8c9 # v2.5.1
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build PyPI & conda nightly binaries
        run: python binaries/build.py --nightly
      - name: Push conda nightly binaries
        env:
          ANACONDA_API_TOKEN: ${{ secrets.CONDA_NIGHTLY_TOKEN }}
        run: python binaries/upload.py --upload-conda-packages
      - name: Push PyPI nightly binaries
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: python binaries/upload.py --upload-pypi-packages
      - name: Open issue on failure
        if: ${{ failure() && github.event_name  == 'schedule' }}
        uses: dacbd/create-issue-action@ba4d1c45cccf9c483f2720cefb40e437f0ee6f7d # v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Nightly Build failed
          body:  Commit ${{ github.sha }} daily scheduled [CI run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) failed, please check why
          assignees: ''
